[build]
  base = ""
  publish = "public/"

[[headers]]
  for = "/*"

  [headers.values]
    Expect-CT = "enforce; max-age=3600"
    Feature-Policy = "geolocation 'none'; notifications 'none'; microphone 'none'; camera 'none'; payment 'none'"
    Referrer-Policy = "strict-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/"
  to = "/whatson"
  status = 301